apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: data-ingress
spec:
  rules:
  - http:
      paths:
      - path: /rate100
        backend:
          serviceName: data-transform
          servicePort: 4000
      - path: /rate-month
        backend:
          serviceName: data-transform2
          servicePort: 4000

