kind: Service
apiVersion: v1
metadata:
  name: data-transform2
  labels:
    app: data-transform2 
spec:
  selector:
    app: data-transform2
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transform2
spec:
  selector:
      matchLabels:
        app: data-transform2
  replicas: 1
  template:
    metadata:
      labels:
        app: data-transform2
    spec:
      imagePullSecrets:
        - name: regcred      
      containers:
        - name: data-transform2
          image: techedgeopensource.azurecr.io/academy/data-transform2:pd
          env:
          - name: PYTHONUNBUFFERED
            value: "0"          
         
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
          livenessProbe:
              httpGet:
                path: /health
                port: 4000           
              initialDelaySeconds: 5
              periodSeconds: 5          
